spring:
  application:
    name: student-service
  profiles:
    active: default
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
