CREATE SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 1;

CREATE TABLE WORKSHOP
(
    ID         integer NOT NULL,
    Title      varchar(255),
    event_date timestamp,
    PRIMARY KEY (ID)
);

CREATE TABLE STUDENT
(
    ID          INTEGER NOT NULL,
    FIRST_NAME  VARCHAR(255),
    LAST_NAME   VARCHAR(255),
    WORKSHOP_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (WORKSHOP_ID) REFERENCES WORKSHOP (ID)

)